# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Xbar_c <- function(gamma, theta, kerMat, meas_times, covariates, censor, n, p) {
    .Call(`_asynlong_Xbar_c`, gamma, theta, kerMat, meas_times, covariates, censor, n, p)
}

H_A_c <- function(gamma, theta, kerMat, meas_times, covariates, response, Xbar, XXtbar, XXtZbar, S0, censor, n, p) {
    .Call(`_asynlong_H_A_c`, gamma, theta, kerMat, meas_times, covariates, response, Xbar, XXtbar, XXtZbar, S0, censor, n, p)
}

long_asy_c <- function(gamma, theta, kerMat, meas_times, covariates, Xbar, XXtbar, response, Hmat, Amat, censor, n, p) {
    .Call(`_asynlong_long_asy_c`, gamma, theta, kerMat, meas_times, covariates, Xbar, XXtbar, response, Hmat, Amat, censor, n, p)
}

countprofun_C <- function(counttime, externalTime) {
    .Call(`_asynlong_countprofun_C`, counttime, externalTime)
}

Xgen_C <- function(covMat, countprocess, p) {
    .Call(`_asynlong_Xgen_C`, covMat, countprocess, p)
}

longest_c <- function(gamma, kerMat, meas_times, covariates, response, dlambda, censor, n, p) {
    .Call(`_asynlong_longest_c`, gamma, kerMat, meas_times, covariates, response, dlambda, censor, n, p)
}

optimtest <- function(z_in, gamma_in) {
    .Call(`_asynlong_optimtest`, z_in, gamma_in)
}

ugamma1_C <- function(kerMat, covariates, n, p) {
    .Call(`_asynlong_ugamma1_C`, kerMat, covariates, n, p)
}

zbar_c <- function(gamma, kerMat, meas_times, covariates, censor, n, p) {
    .Call(`_asynlong_zbar_c`, gamma, kerMat, meas_times, covariates, censor, n, p)
}

ugamma2_C <- function(gamma, kerMat, meas_times, covariates, censor, n, p) {
    .Call(`_asynlong_ugamma2_C`, gamma, kerMat, meas_times, covariates, censor, n, p)
}

dlambda_C <- function(gamma, kerMat, meas_times, covariates, censor, n, p) {
    .Call(`_asynlong_dlambda_C`, gamma, kerMat, meas_times, covariates, censor, n, p)
}

ugamma_C_1 <- function(gamma, kerMat, meas_times, covariates, censor, n, p) {
    .Call(`_asynlong_ugamma_C_1`, gamma, kerMat, meas_times, covariates, censor, n, p)
}

outermin_C <- function(x, y) {
    .Call(`_asynlong_outermin_C`, x, y)
}

epanker_C <- function(u, h) {
    .Call(`_asynlong_epanker_C`, u, h)
}

outerker_C <- function(x, y, h) {
    .Call(`_asynlong_outerker_C`, x, y, h)
}

kerMatgen_C <- function(meas_times, obscov_times, h) {
    .Call(`_asynlong_kerMatgen_C`, meas_times, obscov_times, h)
}

